### ISSUE TITLE
Check tronco.plot for multiple regularizators

### ISSUE THREAD

**Issue by egalimberti** [BIMIB-DISCo/TRONCO#100]
There may be inconsistencies if you run tronco.plot with 2 regularizators but in different orders. 

E.g. tronco.plot(x,models=c("capri_bic","capri_aic") can be different from tronco.plot(x,models=c("capri_aic","capri_bic")

**Comment by caravagn** [comment]
There is no bug there, it is a design choice. The first regularizer gets colored black, the second gray -- there is in fact no way to assign a color to a regularizer in the current implementation. We could consider this suggestion as an improvement -- I switched the label to 'enhancement'.

**Comment by danro9685** [comment]
@caravagn this is not the color difference. If you put reg = c("bic","aic"), tronco.plot puts black the arcs present in both and grey the ones only of aic. Here we are assuming that aic is a superset of bic. If this is not the case, i.e., is bic and aic have arcs and common but also some specific arc in each of them (if regularization 2 is not a superset of 1), then some arcs will disappear from the model whether you do c("bic","aic") or c("aic","bic"). Labelling back to bug.

**Comment by luca-dex** [comment]
This was a design choice. We wanted precisely this behavior  (as described in the documentation)

**Comment by danro9685** [comment]
So we all agree to leave this as is? @caravagn ?
Namely: when you have multiple model, the first model is fixed and its arcs are black. The arcs in the second but not in the first are then shown in grey. 
If you change the order you can also change the visualized arcs, e.g., if the first model is not a subset of the second.
