### ISSUE TITLE
return probabilities of genotypes under model

### ISSUE THREAD

**Issue by rdiaz02** [BIMIB-DISCo/TRONCO#106]
Wish: that TRONCO returns the posterior probabilities of a user-specified set of genotypes under the inferred model.  

I think there are scaling issues (and if we wanted the probability, we'd need to compute the probabilty of all 2^n genotypes, where n is the number of genes), but if we just want to obtain, say, P(genotype A)/P(genotype B), the scaling is not needed.

**Comment by caravagn** [comment]
I believe it is possible to just use bnlearn to return the unormalized probabilities of a list of genotypes; we will look into that asap.

**Comment by rdiaz02** [comment]
Thanks! For now, I might use directly simulating from the Bayesian network with bnlearn, as you showed me a while ago.

```
bn1 <- TRONCO:::as.bnlearn.network(some_tronco_fitted_model))
sim1 <- rbn(bn1$net, number_of_simulated_samples, bn1$data)
```

**Comment by rdiaz02** [comment]
I see this is closed. What is the function that returns the probabilities of genotypes? Looking at the manual I can't find anything.
