### ISSUE TITLE
Error when trying to create a circos plot

### ISSUE THREAD

**Issue by Tato14** [BIMIB-DISCo/TRONCO#107]
Hi! 

I am trying to use the `tronco.pattern.plot` with some MAF data. I get the following error:

Error in matrix(unlist(value, recursive = FALSE, use.names = FALSE), nrow = nr,  : 
  'data' must be of a vector type, was 'NULL'

Any thoughs? Thanks!

**Comment by danro9685** [comment]
Dear @Tato14, 

is seems that there is some missing/empty element in the list of patters. So I guess there must be something wrong with the TRONCO object you are giving as input to the tronco.pattern.plot function. 

For more details, we will need to take a look at the data you are using as inputs. 

Best, 
Daniele

**Comment by Tato14** [comment]
Hi @danro9685 ,

I am completely new with this kind of analysis so I'm quite sure that I forgot something :). Here's an example of the data that I'm working with.

[SM_tumor_merged.maf.zip](https://github.com/BIMIB-DISCo/TRONCO/files/1805689/SM_tumor_merged.maf.zip)

Thank you!

**Comment by danro9685** [comment]
Hi @Tato14, 

the MAF looks apparently good. You imported it with the function import.MAF? 
I have tried to use the import.MAF and then run the tronco.pattern.plot and everything worked fine. 
Can you tell me exactly the commands you run to get the error? 

Best, 
Daniele

**Comment by Tato14** [comment]
Hi @danro9685,

Yes, I used the following commands:
`SMmerged3<- import.MAF("SM_tumor_merged.maf")`
`tronco.pattern.plot(SMmerged3,mode = "circos")`

**Comment by Tato14** [comment]
Sorry, the `tronco.pattern.plot` was:
`tronco.pattern.plot(SMmerged3, to = "Missense_Mutation", mode = "circos")`

**Comment by danro9685** [comment]
Dear @Tato14, 

in the "to" you need to put a gene name. Specifically one of the genes you have in the dataset. 
You can find the list of valid gene names with as.genes(SMmerged3). 

Best, 
Daniele
