### ISSUE TITLE
hits legend in oncoprint not showing up.

### ISSUE THREAD

**Issue by john-s-f** [BIMIB-DISCo/TRONCO#108]
On OSX 10.13.3 (17D47), RStudio 1.1.423, R 3.4.4 (2018-03-15), Bioconductor 3.6 (BiocInstaller 1.28.0), if I run the following in a new R session

`library(BiocInstaller)`
`biocLite("TRONCO")`
`library(TRONCO)`
`oncoprint(aCML)`

Everything works except the bar that's supposed to indicate the amount of hits doesn't have color like it does on page 14 of the vignette, it's supposed to have three shades of purple and one white.
![rplot](https://user-images.githubusercontent.com/37672249/37794812-07b51e06-2de9-11e8-9518-d128c4fe49ff.png)

Changing the colorscale with the below code doesn't do anything either. 
`oncoprint(aCML, hits.color = "Reds"`

I have a feeling it might have to do with the package "gRapHD" because both install.packages("gRapHD) and biocLite("gRapHD) give me "package ‘gRapHD’ is not available (for R version 3.4.4)". So i installed from github using
`install_github("BIMIB-DISCo/TRONCO")`
and that seems to install gRapHD correctly. Previous to doing that I cannot load TRONCO because it says gRapHD is missing.

**Comment by danro9685** [comment]
Dear @john-s-f, 

thank you for letting us know about this issue. We are actually already aware of it and in fact we fixed it in the latest release that you find here on Github. We will also update in on Bioconductor before the next release. 

Thanks, 
Daniele
