### ISSUE TITLE
gRapHD dependency

### ISSUE THREAD

**Issue by rdiaz02** [BIMIB-DISCo/TRONCO#109]
Apparently, gRapHD is no longer (2018-02-12) available (https://cran.r-project.org/web//packages/gRapHD/index.html) and that precludes installing TRONCO using the BioC default procedure (requires manually downloading and installing gRapHD from https://cran.r-project.org/src/contrib/Archive/gRapHD/)

**Comment by danro9685** [comment]
Dear @rdiaz02, 

we are aware of the issue which will be fixed in the next release. 
Thank you for letting us know. 

Best, 
Daniele
