### ISSUE TITLE
How to arrange the sample in oncoplrint

### ISSUE THREAD

**Issue by beginner984** [BIMIB-DISCo/TRONCO#119]
Hi

I have two groups of patients, responders to a drug and non responders

I have a list of GISTIC genes for them

by this I plotted an oncoplot

`oncoprint(dataset_gistic,pattern=TRUE,annotate.consolidate.events=TRUE,sample.id=TRUE,samples.cluster=TRUE)`

![Rplot07](https://user-images.githubusercontent.com/43682980/77336173-0dbb1680-6d1f-11ea-8392-9c903239c5e1.png)

But I want samples of each groups being together

How I can do that please?
[c1.txt](https://github.com/BIMIB-DISCo/TRONCO/files/4370456/c1.txt)

**Comment by caravagn** [comment]
In Fig 2 of [the vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/TRONCO/inst/doc/vignette.pdf) we use the idea of groups to impose a clustering of the columns, would that work for you?

**Comment by caravagn** [comment]
Other options is to disable sample's clustering and pass a dataset that is created with the samples  in the required ordering?

**Comment by beginner984** [comment]
Thank you so much

Actually I a bit confused

I have 15 responders samples and 33 non responders samples

and 9 genes for them (same genes)

Of course the percentage of hits is different for a given genes in each group

If I plot them together for instance hits for CDKN2A is 33% 

But when I plot them separately hits is different

For examples this is responders

![Rplot12](https://user-images.githubusercontent.com/43682980/77337505-e36a5880-6d20-11ea-898d-c1be9e56c86c.png)

And this is non responders

![Rplot13](https://user-images.githubusercontent.com/43682980/77337540-ee24ed80-6d20-11ea-9e8a-90501b3139e1.png)

My goal is to show that CDKN2A copy number is different between groups but I don't know how to convey this message

**Comment by beginner984** [comment]
> sample's clustering

How to disable sample clustering?

**Comment by danro9685** [comment]
Dear @beginner984, 

in the oncoprint function, the parameter excl.sort (default TRUE) enables sorting of samples by mutation profiles. You can order your samples as you like as suggested by @caravagn prior to data import in TRONCO and then disable excl.sort (set it to FALSE) when generating oncoprint. 

Best, 
Daniele

**Comment by beginner984** [comment]
Hello

I have `a fix set of genes` plotted across `two distinct groups`, because the alteration frequency is not the same for a given gene, the order of genes in two plots is not the same so makes eye comparisons difficult
One solution is plotting samples from two groups together but this does not work for purpose of comparison 

How I can maintain all genes in plots even if `the alteration is zero`?
For instance `PTEN` has `homozygous deletion` in one group without `homozygous deletion` in another group so `PTEN` being removed from one group but I want to be remained 

![Rplot12](https://user-images.githubusercontent.com/43682980/80616637-0df2b400-8a39-11ea-8515-1a314cffdfac.png)

![Rplot67](https://user-images.githubusercontent.com/43682980/80616739-2a8eec00-8a39-11ea-8b7d-e224ff0126b3.png)

`oncoprint(dataset_gistic,excl.sort =FALSE,samples.cluster = FALSE,genes.cluster = FALSE)
`
Thank you for any help

**Comment by danro9685** [comment]
Dear @beginner984, 

you need to import differently your data. Either you make in R data matrices with your genes (also including mutations with 0s) and import them with the import.genotypes function or if you want to use import.GISTIC, you find the parameter trim which is TRUE by default. If you set it to FALSE, it will keep entries with all 0s, import.GISTIC(data,trim=FALSE). 

Best, 
Daniele

**Comment by beginner984** [comment]
Sorry the problem is when for example PTEN has no homozygous deletion in one group there is no rows says homozygous deletion for PTEN is 0% therefore the arrange among the group is uneven because one group have homozygous deletion for PTEN one group does not. I am wondering if we can place rows says 0% for homozygous deletion, heterozygous deletion, high level amplification and low level amplification so that the arrange of genes in individual oncoprints for different groups with a fixed number of genes is the same and comparable.
