### ISSUE TITLE
Showing an oncoplot in a side by side view

### ISSUE THREAD

**Issue by beginner984** [BIMIB-DISCo/TRONCO#120]
Hi

Indeed, this is nt an issue with your software rather my query about the possibility of a sort of visualisation

Please, you imagine I have two groups of patients for which I want to look at mutations in a fixed set of genes

That would be great if one could show hits and type of mutation for each gene in each group in a way to be comparable like the below figure 

![Picture](https://user-images.githubusercontent.com/43682980/77422008-b1123700-6dc4-11ea-97e3-b41ae5b36346.png)

If there any function in your software to make this possible? If not do you have any suggestion to achieve such an view?

Thanks in advance

**Comment by caravagn** [comment]
Hi, TRONCO does not have such a function. You can however obtained that plot easily with `ggplot`, see [here for instance](https://stackoverflow.com/questions/6999144/how-do-you-create-a-bar-plot-for-two-variables-mirrored-across-the-x-axis-in-r) for instance (then use `coord_flip` and `ylim` to achieve your squared rotated layout.

Does this help?

**Comment by caravagn** [comment]
Btw, you can normalise the data if you want first. It would be the same plot.
