### ISSUE TITLE
How can I place hits for an individual gene next to each other

### ISSUE THREAD

**Issue by beginner984** [BIMIB-DISCo/TRONCO#121]
Hi

I have plotted as below by your nice software

![Picture](https://user-images.githubusercontent.com/43682980/77833435-37b47480-7135-11ea-8b03-08b60177a8cc.png)

Is it possible to place, for instance, heterozygous and homozygous copy number for CDKN2A close to each other? I mean for example first row is heterozygous deletion for CDKN2A and second row is homozygous deletion for CDKN2A, and for all genes like this

Thanks for any help

**Comment by caravagn** [comment]
If you disabled row clustering, you can just order (any way you want) the input matrix, and pass it to the plot function.
