### ISSUE TITLE
Using CAPRI’s functioning by my own data

### ISSUE THREAD

**Issue by beginner984** [BIMIB-DISCo/TRONCO#124]
Hello

In your vignette, you are mentioning `aCML` data as input for `CAPRI’s functioning`, I don't know how to make such an object. However, I have my own data in` maf`, `GISTIC` and `boolean matrix` 

How I pass/modify my own data in CAPRI in a way which aCML data works?

Thank you

**Comment by caravagn** [comment]
Hi @beginner984. Did you check if the [TRONCO vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/TRONCO/inst/doc/vignette.pdf) does not explain how to run that analysis?
