### ISSUE TITLE
Misuse of `events.selection`?

### ISSUE THREAD

**Issue by marcoxa** [BIMIB-DISCo/TRONCO#129]
Hi giovini!

one of my students got this point having downloaded the COAD and the READ datasets using `TCGAbiolinks`.
```
> colo_data = events.selection(colo_data,  filter.freq = .05,
+                              filter.in.names = c("Wnt","RAS","PI3K","TGFb","P53"))
*** Events selection: #events =  19786 , #types =  1 Filters freq|in|out = { TRUE ,  TRUE ,  FALSE }
Minimum event frequency:  0.05  ( 20  alterations out of  399  samples).
...
Selected  2828  events.
```
Of course, 2828 "events" are too many.
The student may have made some mistake; note that he passes in the pathways names (which as vectors of genes).  The question is whether this is the most appropriate use of `events.selection`.

Any ideas?

MA

**Comment by luca-dex** [comment]
Can you attach an oncoprint of `colo_data` ?

**Comment by marcoxa** [comment]
Here it is

![colo_data_oncoprint](https://user-images.githubusercontent.com/514394/101372595-5c5c1100-38ac-11eb-9d19-e9095b786677.jpeg)

**Comment by marcoxa** [comment]
Scusate.... ma perchè "closed"?

**Comment by luca-dex** [comment]
Sorry, probably it was an error. However from the picture it is not possible to see percentages. In the meantime I had to move to Karachi... 

Event selection only count the amount of mutation / number of samples, so it is quite difficult that there can be an error.

Did the student checked the values manually, just to kmow if numbers are correct?

**Comment by danro9685** [comment]
@marcoxa try just as a sanity check, to perform the two filtering steps separately (the 5% step and pathway names one). It is also very possible that in the data you have lots of variants with these characteristics (either >=5% or in these pathways). 

@luca-dex please confirm, but I believe the filter is an "OR", meaning either of the 2 conditions, right?

**Comment by danro9685** [comment]
@marcoxa I have double checked and can confirm that there is no error in the function, you simply selected too many genes. 

Colorectal cancer has high mutational burden and here we have an average of approx 80 variants per patient. If you use this filters, these number are expected. Either increase the filtering threshold or give a list of pre-defined genes as names.
