### ISSUE TITLE
PiCnIc/TRONCO for different samples of the same tumor

### ISSUE THREAD

**Issue by Tato14** [BIMIB-DISCo/TRONCO#134]
Thanks for the great tool. 

I see in you [supplementary](https://www.pnas.org/doi/10.1073/pnas.1520213113#supplementary-materials) from PiCnIc paper that you performed clonal evolution on COAD dataset. However, you mention in the paper that the same pipeline could be performed using different samples from the same patient (Fig 1 A Right). 

I have this scenario and I would like to know if you could point me to a resource in order to perform this kind of analysis.

**Comment by caravagn** [comment]
At this point imho you would be treating the samples as independent, as the PiCnIc model had no advanced model for multi-sample data. 

@danro9685 maybe can propose something more modern.

**Comment by danro9685** [comment]
Hi,

I agree with @caravagn.
@Tato14  you could use the PiCnIc approach but here we did not explicitly modeled multi-sample data.

It is hard to say without more information on your data and aims. If you have bulk data with only some multi-sample patient, you could give PiCnIc a try.

Instead, if you have full multi-region data, I believe REVOLVER by @caravagn would be the way (see https://www.nature.com/articles/s41592-018-0108-x and https://caravagnalab.github.io/revolver/index.html).

Depending on your objectives and data, you could also apply our latest framework, ASCETIC (see https://www.nature.com/articles/s41467-023-41670-3 and https://github.com/danro9685/ASCETIC), maybe also in combination with REVOLVER for the phylogenetic inference part.

Let us know if you have more questions.

All the best,
Daniele

**Comment by Tato14** [comment]
Hi,

Thanks for the insightful response. I have results from a Foundation like NGS panel coming from multi-region data of the same patient. I guess it could be similar to the [CRC vignette](https://caravagnalab.github.io/revolver/articles/Cross_CRC_MSeq.html) from REVOLVER. 

However, I am unsure how to annotate the different variants I got from the different multi region samples. I see in the [REVOLVER FAQ](https://caravagnalab.github.io/revolver/articles/FAQ.html#what-kind-of-data-can-i-use-to-run-revolver) that you can generate CCF values using different softwares. However, I am unsure how to generate this results from multi-region data. Should I consider every sample as an individual, or, there is any way to use the mult-sample information to infer better the CCF? There is any recommendation on the software I should use? 

I see MOBSTER is developed by your group too. It somehow consider this multisample issue or is REVOLVER the one accounting for this feature?

Thanks

**Comment by caravagn** [comment]
Hello @Tato14 i would suggest you use pyClone to get CCFs from multiregiobn data, if you have copy number data. Do you have it?

Otherwise yeah you can go as for the CRC example on revolver. However CCFs are generally better imho.

**Comment by Tato14** [comment]
Hi @caravagn, I have some copy number estimates but this does not apply to all regions and variants. I could use the closest estimate for each mutation but it will be great if there could be another approach. Do you have any alternative that uses multi-region SNV without considering copy number?

Also, I am unable to find the syntaxis to input multi region sample in pyClone. I found [pyClone-vi](https://github.com/Roth-Lab/pyclone-vi) which seems to consider `sample_id` for this multi-region analysis. Should I use this one?
