### ISSUE TITLE
as.kfold.posterr returns a data frame with all columns as characters

### ISSUE THREAD

**Issue by rdiaz02** [BIMIB-DISCo/TRONCO#70]
I do not think that is intended as the columns for MEAN.POSTERR and SD.POSTERR are also of type character, not numeric. In fact, that this is happening can be seen also in the vignette, p. 37. This is inconvenient, and inconsistent with prederr.

Example:
```
data(test_model_kfold)
s1 <- as.kfold.posterr(test_model_kfold)
summary(s1[[1]])
summary(s1[[2]])
```

**Comment by luca-dex** [comment]
Thanks @rdiaz02 , 	2724bb1 fix the problem
