### ISSUE TITLE
PICNIC/COADREAD crashes at step 5, statistics, line 115.

### ISSUE THREAD

**Issue by caravagn** [BIMIB-DISCo/TRONCO#78]
PICNIC/COADREAD crashes at step 5, statistics, line 115.

Reason

> MSS.models$kfold$bic
NULL
> names(MSS.models$kfold)
[1] "capri_bic" "capri_aic"

Change of names should be fixed.

**Comment by luca-dex** [comment]
`bic` -> `capri_bic`
