### ISSUE TITLE
export.graphML and output graph format

### ISSUE THREAD

**Issue by CostantiniMatteo** [BIMIB-DISCo/TRONCO#85]
Hi,

me and Lucrezia Patruno will soon start to work on cyTRON as a project for our thesis with professor Marco Antoniotti. We are opening this issue because the TRONCO library doesn't implement the function export.graphML used to import the graph into Cytoscape. We would like to know if it's possible to have an implementation of the function and if other formats can be supported.

Thanks.
Matteo Costantini and Lucrezia Patruno

**Comment by luca-dex** [comment]
I don't understand the request. The function is available at
https://github.com/BIMIB-DISCo/TRONCO/blob/master/R/external.R#L481
